options:
    formatter: stylish
    merge-default-rules: true

rules:
    class-name-format:
        - 0
    clean-import-paths:
        - 1
        - leading-underscore: true
    force-attribute-nesting:
        - 0
    force-element-nesting:
        - 0
    force-pseudo-nesting:
        - 0
    indentation:
        - 1
        - size: 4
    mixins-before-declarations:
        - 0
    no-ids:
        - 0
    no-important:
        - 0
    no-qualifying-elements:
        - 0
    nesting-depth:
        - 0
    property-sort-order:
        - 0
